global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts/oracle.yml"

scrape_configs:
  - job_name: "floww-oracle"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
